<a href="https://colab.research.google.com/github/sriraj934/Combined_cycle_Power_Plant-for-Regression-ANN-/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 , random_state = 0)

In [7]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [8]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [9]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [10]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [13]:
print(X_test)

[[ 1.20924389  1.84743445 -0.61878043 -0.28968211]
 [-0.29401214 -0.39528045  1.39211729  0.76937061]
 [-0.64629575 -0.88607065  1.00508258  1.77019599]
 ...
 [-0.99857936 -0.74629361  1.76737267  1.02146078]
 [ 1.02368993 -0.50992904 -1.64526378 -0.96443434]
 [-0.32090402 -1.13342892 -1.03442205  0.0651622 ]]


## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
ann =tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

### Adding the second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

### Adding the output layer

In [17]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
ann.compile(optimizer='adam',loss='mean_squared_error')

### Training the ANN on the Training set

In [19]:
classifier = ann.fit(X_train , y_train , batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 955us/step - loss: 207142.7623
Epoch 2/100
240/240 [==============================] - 0s 987us/step - loss: 205590.9486
Epoch 3/100
240/240 [==============================] - 0s 995us/step - loss: 198645.9122
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 177033.4466
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 142270.5942
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 102874.9403
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 66137.1342
Epoch 8/100
240/240 [==============================] - 0s 963us/step - loss: 41750.6296
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 28890.6639
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 23302.1300
Epoch 11/100
240/240 [==============================] - 0s 988us/step - loss: 20005.2404
Epoch 12/100
240/240 [==============

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[431.09 431.23]
 [458.84 460.01]
 [463.33 461.14]
 ...
 [469.89 473.26]
 [442.06 438.  ]
 [461.86 463.28]]


In [21]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9354984333874737